#!/bin/bash

image_uri="/home/<username>/Images/natgeo.jpg"
historic_folder="/home/<username>/Images/natgeo/"

# Get url of image of the day
url=$(curl -s http://www.nationalgeographic.com/photography/_jcr_content/content/multilayout_8.promo-all.json | jq -r '.[0].leadMedia.url')
# Get image
wget $url -O $image_uri

# Uncomment if you want a history
cp $image_uri $historic_folder$(date +%d-%m-%Y).jpg
